ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE IF EXISTS users ADD COLUMN IF NOT EXISTS role VARCHAR(20);

ALTER TABLE IF EXISTS anime ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE IF EXISTS anime ADD COLUMN IF NOT EXISTS year VARCHAR(20);
ALTER TABLE IF EXISTS anime ADD COLUMN IF NOT EXISTS genre VARCHAR(255);
ALTER TABLE IF EXISTS anime ADD COLUMN IF NOT EXISTS poster_url TEXT;
ALTER TABLE IF EXISTS anime ADD COLUMN IF NOT EXISTS trailer_url TEXT;

ALTER TABLE IF EXISTS episode ADD COLUMN IF NOT EXISTS anime_id INT;
ALTER TABLE IF EXISTS episode ADD COLUMN IF NOT EXISTS episode_number INT;
ALTER TABLE IF EXISTS episode ADD COLUMN IF NOT EXISTS video_url TEXT;

ALTER TABLE IF EXISTS favorites ADD COLUMN IF NOT EXISTS user_id VARCHAR(36);
ALTER TABLE IF EXISTS favorites ADD COLUMN IF NOT EXISTS anime_id INT;

ALTER TABLE IF EXISTS forgot_password ADD COLUMN IF NOT EXISTS otp INT;
ALTER TABLE IF EXISTS forgot_password ADD COLUMN IF NOT EXISTS expiration_time TIMESTAMP;
ALTER TABLE IF EXISTS forgot_password ADD COLUMN IF NOT EXISTS reset_token VARCHAR(255);
ALTER TABLE IF EXISTS forgot_password ADD COLUMN IF NOT EXISTS user_id VARCHAR(36);
